### ISSUE TITLE
get_encoders() got an unexpected keyword argument 'use_adapter'

### ISSUE THREAD

**Issue by CoinCheung** [hecongqing/CCKS2019_EventEntityExtraction_Rank5#4]
Hi, 

Thanks for releasing the codebase !!

I installed tensorflow-gpu1.14.0 and keras2.2.4 and keras-bert0.69.0. When I run the script, I got the error of: 
```
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "SEBERT_model.py", line 458, in <module>
    model, train_model = modify_bert_model_3()
  File "SEBERT_model.py", line 243, in modify_bert_model_3
    bert_model = load_trained_model_from_checkpoint(config_path, checkpoint_path)
  File "/miniconda/envs/tf114/lib/python3.6/site-packages/keras_bert/loader.py", line 182, in load_trained_model_from_checkpoint
    adapter_units=adapter_units,
  File "/miniconda/envs/tf114/lib/python3.6/site-packages/keras_bert/loader.py", line 62, in build_model_from_config
    adapter_units=adapter_units,
  File "/miniconda/envs/tf114/lib/python3.6/site-packages/keras_bert/bert.py", line 117, in get_model
    adapter_activation=gelu,
TypeError: get_encoders() got an unexpected keyword argument 'use_adapter'
```

I am not familiar with keras or keras-bert,  would you please tell how to make it work ?

**Comment by CoinCheung** [comment]
Solved.
